version: '3'
networks:
  db:
  services:
  web:
services:
  ristorante-db:
    restart: always
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongodb/cdals:/data/db
      - /etc/localtime:/etc/localtime:ro
    networks:
      - db  

  ristorante-back:
    restart: always
    build: ./ristorante-back
    image: ristorante
    environment:
      - DB_SERVER=ristorante-db
      - DB_NAME=ristorante-menu
      - PORT=80
    depends_on:
      - ristorante-db
    ports:
      - 5000:80
    networks:
      - db
      - services
      - web
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: 500m 


  # frontend:
  #   restart: always
  #   build: ./ristorante-front
  #   networks:
  #     - web
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - /etc/localtime:/etc/localtime:ro
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - ristorante-back
  #   ports:
  #     - 80:80
